{% set name = "pyubxutils" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyubxutils-{{ version }}.tar.gz
  sha256: 4919e65bd7f9000b30f22bec63e4811c2a6787123ef577eb2908b7731b79ba89
build:
  entry_points:
    - ubxsetrate = pyubxutils.ubxsetrate:main
    - ubxsave = pyubxutils.ubxsave:main
    - ubxload = pyubxutils.ubxload:main
    - ubxbase = pyubxutils.ubxbase:main
    - ubxsimulator = pyubxutils.ubxsimulator_cli:main
    - ubxcompare = pyubxutils.ubxcompare:main

  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=66.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pyserial >=3.5
    - pyubx2 >=1.2.48

test:
  imports:
    - pyubxutils
  commands:
    - pip check
    - ubxsimulator --help
    - ubxsetrate --help
    - ubxsave --help
    - ubxload --help
    - ubxbase --help
    - ubxcompare --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/semuconsulting/pyubxutils
  description: Python UBX GNSS CLI utility library.
  summary: Python GNSS CLI utility library.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pyubxutils
  dev_url: https://github.com/semuconsulting/pyubxutils

extra:
  recipe-maintainers:
    - semuadmin
